// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v5.29.1
// source: notification.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Format, formatFromJSON, formatToJSON } from "./formats/formats";
import { Timestamp } from "./google/protobuf/timestamp";
import { Parameter, Target, targetFromJSON, targetToJSON } from "./parameters/parameters";
import { NotificationType, notificationTypeFromJSON, notificationTypeToJSON } from "./types/types";

export const protobufPackage = "notification";

export enum Importance {
  /** NOT_USED1 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED1 = 0,
  NORMAL = 1,
  IMPORTANT = 2,
  CRITICAL = 3,
  UNRECOGNIZED = -1,
}

export function importanceFromJSON(object: any): Importance {
  switch (object) {
    case 0:
    case "NOT_USED1":
      return Importance.NOT_USED1;
    case 1:
    case "NORMAL":
      return Importance.NORMAL;
    case 2:
    case "IMPORTANT":
      return Importance.IMPORTANT;
    case 3:
    case "CRITICAL":
      return Importance.CRITICAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Importance.UNRECOGNIZED;
  }
}

export function importanceToJSON(object: Importance): string {
  switch (object) {
    case Importance.NOT_USED1:
      return "NOT_USED1";
    case Importance.NORMAL:
      return "NORMAL";
    case Importance.IMPORTANT:
      return "IMPORTANT";
    case Importance.CRITICAL:
      return "CRITICAL";
    case Importance.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Exist {
  Exists: boolean;
}

export interface UnreadResponse {
  HasUnread: boolean;
}

export interface Notifications {
  Notification: Notification[];
  More: More | undefined;
}

export interface More {
  ID: number;
  TS: number;
}

/**
 * Notifications can be high level: Give me NFT Like notifications on my NFTs, or low level: Let me know when collection XYZ is updated
 * The absence or presence of the ID field determines the level of notification
 */
export interface Notification {
  /** Has a meaning if combined with the Type */
  ID: string;
  /** Recipient is either a user or an admin */
  RecipientID?: string | undefined;
  Type: NotificationType;
  Message: Message | undefined;
  CreatedAt: Date | undefined;
  UpdatedAt:
    | Date
    | undefined;
  /** Unique ID used for Read notifications matching. Timestamp in nanos assigned by the storage layer */
  NotificationID: number;
  /** Default false. Used for personal messages read state, merged with Read state from message Read */
  Read: boolean;
  /** AccountID of the sender of the message (if applicable) */
  From: string;
  /** Default Normal */
  Importance: Importance;
  /** Default none */
  Target: Target[];
  /** Default none, used for admin/system/marketing notifications so those can be filtered */
  ExpiresAt:
    | Date
    | undefined;
  /** Default none, used for admin/system/marketing notifications so those can be filtered */
  ValidFrom:
    | Date
    | undefined;
  /** Unique sender generated stable key (prevents duplicate notifications) */
  Key: string;
  OrganizationID: string;
}

export interface Message {
  Format: Format;
  Subject: string;
  Body: string;
  Parameter: Parameter[];
}

function createBaseExist(): Exist {
  return { Exists: false };
}

export const Exist = {
  encode(message: Exist, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Exists !== false) {
      writer.uint32(8).bool(message.Exists);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Exist {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExist();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Exists = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Exist {
    return { Exists: isSet(object.Exists) ? globalThis.Boolean(object.Exists) : false };
  },

  toJSON(message: Exist): unknown {
    const obj: any = {};
    if (message.Exists !== false) {
      obj.Exists = message.Exists;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Exist>, I>>(base?: I): Exist {
    return Exist.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Exist>, I>>(object: I): Exist {
    const message = createBaseExist();
    message.Exists = object.Exists ?? false;
    return message;
  },
};

function createBaseUnreadResponse(): UnreadResponse {
  return { HasUnread: false };
}

export const UnreadResponse = {
  encode(message: UnreadResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.HasUnread !== false) {
      writer.uint32(8).bool(message.HasUnread);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UnreadResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnreadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.HasUnread = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnreadResponse {
    return { HasUnread: isSet(object.HasUnread) ? globalThis.Boolean(object.HasUnread) : false };
  },

  toJSON(message: UnreadResponse): unknown {
    const obj: any = {};
    if (message.HasUnread !== false) {
      obj.HasUnread = message.HasUnread;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnreadResponse>, I>>(base?: I): UnreadResponse {
    return UnreadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnreadResponse>, I>>(object: I): UnreadResponse {
    const message = createBaseUnreadResponse();
    message.HasUnread = object.HasUnread ?? false;
    return message;
  },
};

function createBaseNotifications(): Notifications {
  return { Notification: [], More: undefined };
}

export const Notifications = {
  encode(message: Notifications, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Notification) {
      Notification.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.More !== undefined) {
      More.encode(message.More, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notifications {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotifications();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Notification.push(Notification.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.More = More.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notifications {
    return {
      Notification: globalThis.Array.isArray(object?.Notification)
        ? object.Notification.map((e: any) => Notification.fromJSON(e))
        : [],
      More: isSet(object.More) ? More.fromJSON(object.More) : undefined,
    };
  },

  toJSON(message: Notifications): unknown {
    const obj: any = {};
    if (message.Notification?.length) {
      obj.Notification = message.Notification.map((e) => Notification.toJSON(e));
    }
    if (message.More !== undefined) {
      obj.More = More.toJSON(message.More);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notifications>, I>>(base?: I): Notifications {
    return Notifications.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notifications>, I>>(object: I): Notifications {
    const message = createBaseNotifications();
    message.Notification = object.Notification?.map((e) => Notification.fromPartial(e)) || [];
    message.More = (object.More !== undefined && object.More !== null) ? More.fromPartial(object.More) : undefined;
    return message;
  },
};

function createBaseMore(): More {
  return { ID: 0, TS: 0 };
}

export const More = {
  encode(message: More, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== 0) {
      writer.uint32(8).int64(message.ID);
    }
    if (message.TS !== 0) {
      writer.uint32(16).int64(message.TS);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): More {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMore();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.ID = longToNumber(reader.int64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.TS = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): More {
    return {
      ID: isSet(object.ID) ? globalThis.Number(object.ID) : 0,
      TS: isSet(object.TS) ? globalThis.Number(object.TS) : 0,
    };
  },

  toJSON(message: More): unknown {
    const obj: any = {};
    if (message.ID !== 0) {
      obj.ID = Math.round(message.ID);
    }
    if (message.TS !== 0) {
      obj.TS = Math.round(message.TS);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<More>, I>>(base?: I): More {
    return More.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<More>, I>>(object: I): More {
    const message = createBaseMore();
    message.ID = object.ID ?? 0;
    message.TS = object.TS ?? 0;
    return message;
  },
};

function createBaseNotification(): Notification {
  return {
    ID: "",
    RecipientID: undefined,
    Type: 0,
    Message: undefined,
    CreatedAt: undefined,
    UpdatedAt: undefined,
    NotificationID: 0,
    Read: false,
    From: "",
    Importance: 0,
    Target: [],
    ExpiresAt: undefined,
    ValidFrom: undefined,
    Key: "",
    OrganizationID: "",
  };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ID !== "") {
      writer.uint32(10).string(message.ID);
    }
    if (message.RecipientID !== undefined) {
      writer.uint32(18).string(message.RecipientID);
    }
    if (message.Type !== 0) {
      writer.uint32(24).int32(message.Type);
    }
    if (message.Message !== undefined) {
      Message.encode(message.Message, writer.uint32(34).fork()).ldelim();
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(42).fork()).ldelim();
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(50).fork()).ldelim();
    }
    if (message.NotificationID !== 0) {
      writer.uint32(64).int64(message.NotificationID);
    }
    if (message.Read !== false) {
      writer.uint32(72).bool(message.Read);
    }
    if (message.From !== "") {
      writer.uint32(82).string(message.From);
    }
    if (message.Importance !== 0) {
      writer.uint32(88).int32(message.Importance);
    }
    writer.uint32(98).fork();
    for (const v of message.Target) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.ExpiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.ExpiresAt), writer.uint32(106).fork()).ldelim();
    }
    if (message.ValidFrom !== undefined) {
      Timestamp.encode(toTimestamp(message.ValidFrom), writer.uint32(114).fork()).ldelim();
    }
    if (message.Key !== "") {
      writer.uint32(122).string(message.Key);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(130).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.RecipientID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Message = Message.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.NotificationID = longToNumber(reader.int64() as Long);
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.Read = reader.bool();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.From = reader.string();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.Importance = reader.int32() as any;
          continue;
        case 12:
          if (tag === 96) {
            message.Target.push(reader.int32() as any);

            continue;
          }

          if (tag === 98) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.Target.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.ExpiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.ValidFrom = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.Key = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      RecipientID: isSet(object.RecipientID) ? globalThis.String(object.RecipientID) : undefined,
      Type: isSet(object.Type) ? notificationTypeFromJSON(object.Type) : 0,
      Message: isSet(object.Message) ? Message.fromJSON(object.Message) : undefined,
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
      NotificationID: isSet(object.NotificationID) ? globalThis.Number(object.NotificationID) : 0,
      Read: isSet(object.Read) ? globalThis.Boolean(object.Read) : false,
      From: isSet(object.From) ? globalThis.String(object.From) : "",
      Importance: isSet(object.Importance) ? importanceFromJSON(object.Importance) : 0,
      Target: globalThis.Array.isArray(object?.Target) ? object.Target.map((e: any) => targetFromJSON(e)) : [],
      ExpiresAt: isSet(object.ExpiresAt) ? fromJsonTimestamp(object.ExpiresAt) : undefined,
      ValidFrom: isSet(object.ValidFrom) ? fromJsonTimestamp(object.ValidFrom) : undefined,
      Key: isSet(object.Key) ? globalThis.String(object.Key) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.RecipientID !== undefined) {
      obj.RecipientID = message.RecipientID;
    }
    if (message.Type !== 0) {
      obj.Type = notificationTypeToJSON(message.Type);
    }
    if (message.Message !== undefined) {
      obj.Message = Message.toJSON(message.Message);
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    if (message.NotificationID !== 0) {
      obj.NotificationID = Math.round(message.NotificationID);
    }
    if (message.Read !== false) {
      obj.Read = message.Read;
    }
    if (message.From !== "") {
      obj.From = message.From;
    }
    if (message.Importance !== 0) {
      obj.Importance = importanceToJSON(message.Importance);
    }
    if (message.Target?.length) {
      obj.Target = message.Target.map((e) => targetToJSON(e));
    }
    if (message.ExpiresAt !== undefined) {
      obj.ExpiresAt = message.ExpiresAt.toISOString();
    }
    if (message.ValidFrom !== undefined) {
      obj.ValidFrom = message.ValidFrom.toISOString();
    }
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.ID = object.ID ?? "";
    message.RecipientID = object.RecipientID ?? undefined;
    message.Type = object.Type ?? 0;
    message.Message = (object.Message !== undefined && object.Message !== null)
      ? Message.fromPartial(object.Message)
      : undefined;
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    message.NotificationID = object.NotificationID ?? 0;
    message.Read = object.Read ?? false;
    message.From = object.From ?? "";
    message.Importance = object.Importance ?? 0;
    message.Target = object.Target?.map((e) => e) || [];
    message.ExpiresAt = object.ExpiresAt ?? undefined;
    message.ValidFrom = object.ValidFrom ?? undefined;
    message.Key = object.Key ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    return message;
  },
};

function createBaseMessage(): Message {
  return { Format: 0, Subject: "", Body: "", Parameter: [] };
}

export const Message = {
  encode(message: Message, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Format !== 0) {
      writer.uint32(8).int32(message.Format);
    }
    if (message.Subject !== "") {
      writer.uint32(18).string(message.Subject);
    }
    if (message.Body !== "") {
      writer.uint32(26).string(message.Body);
    }
    for (const v of message.Parameter) {
      Parameter.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Message {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Format = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Subject = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Body = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Parameter.push(Parameter.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      Format: isSet(object.Format) ? formatFromJSON(object.Format) : 0,
      Subject: isSet(object.Subject) ? globalThis.String(object.Subject) : "",
      Body: isSet(object.Body) ? globalThis.String(object.Body) : "",
      Parameter: globalThis.Array.isArray(object?.Parameter)
        ? object.Parameter.map((e: any) => Parameter.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.Format !== 0) {
      obj.Format = formatToJSON(message.Format);
    }
    if (message.Subject !== "") {
      obj.Subject = message.Subject;
    }
    if (message.Body !== "") {
      obj.Body = message.Body;
    }
    if (message.Parameter?.length) {
      obj.Parameter = message.Parameter.map((e) => Parameter.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.Format = object.Format ?? 0;
    message.Subject = object.Subject ?? "";
    message.Body = object.Body ?? "";
    message.Parameter = object.Parameter?.map((e) => Parameter.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
