// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v5.29.1
// source: notification-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Empty } from "./google/protobuf/Empty";
import { Exist, Notification, Notifications, UnreadResponse } from "./notification";
import { NotificationType, notificationTypeFromJSON, notificationTypeToJSON } from "./types/types";

export const protobufPackage = "notification";

export interface TopRequest {
  RecipientID: string;
  Type: NotificationType[];
  OrganizationID?:
    | string
    | undefined;
  /** Used to fetch notifications for a user: fetching broadcast type notifications should be relative to when the user was created. */
  From?: number | undefined;
}

export interface UnreadRequest {
  RecipientID: string;
  OrganizationID: string;
  /** Used to fetch notifications for a user: fetching broadcast type notifications should be relative to when the user was created. */
  From?: number | undefined;
}

/**
 * ListRequest defines the filters for fetching notifications:
 *  - if neither OrganizationID nor RecipientID is provided, the request is for syste-wide notifications (sologenic_admin notifications)
 *  - if only OrganizationID is provided, the request is for an organization's notifications + system-wide notifications
 *  - if both OrganizationID and RecipientID are provided, the request is for an individual user's notifications + user's organization notifications + system-wide notifications
 */
export interface ListRequest {
  RecipientID?: string | undefined;
  NotificationID: number;
  OrganizationID?:
    | string
    | undefined;
  /** Used to fetch notifications for a user: fetching broadcast type notifications should be relative to when the user was created. */
  From?: number | undefined;
}

export interface ReadRequest {
  RecipientID: string;
  Key: string[];
  OrganizationID: string;
}

export interface ReadAllRequest {
  RecipientID: string;
  OrganizationID: string;
}

export interface Key {
  Key: string;
}

function createBaseTopRequest(): TopRequest {
  return { RecipientID: "", Type: [], OrganizationID: undefined, From: undefined };
}

export const TopRequest = {
  encode(message: TopRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.RecipientID !== "") {
      writer.uint32(10).string(message.RecipientID);
    }
    writer.uint32(18).fork();
    for (const v of message.Type) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.OrganizationID !== undefined) {
      writer.uint32(26).string(message.OrganizationID);
    }
    if (message.From !== undefined) {
      writer.uint32(32).int64(message.From);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TopRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTopRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.RecipientID = reader.string();
          continue;
        case 2:
          if (tag === 16) {
            message.Type.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.Type.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.From = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TopRequest {
    return {
      RecipientID: isSet(object.RecipientID) ? globalThis.String(object.RecipientID) : "",
      Type: globalThis.Array.isArray(object?.Type) ? object.Type.map((e: any) => notificationTypeFromJSON(e)) : [],
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      From: isSet(object.From) ? globalThis.Number(object.From) : undefined,
    };
  },

  toJSON(message: TopRequest): unknown {
    const obj: any = {};
    if (message.RecipientID !== "") {
      obj.RecipientID = message.RecipientID;
    }
    if (message.Type?.length) {
      obj.Type = message.Type.map((e) => notificationTypeToJSON(e));
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.From !== undefined) {
      obj.From = Math.round(message.From);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TopRequest>, I>>(base?: I): TopRequest {
    return TopRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TopRequest>, I>>(object: I): TopRequest {
    const message = createBaseTopRequest();
    message.RecipientID = object.RecipientID ?? "";
    message.Type = object.Type?.map((e) => e) || [];
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.From = object.From ?? undefined;
    return message;
  },
};

function createBaseUnreadRequest(): UnreadRequest {
  return { RecipientID: "", OrganizationID: "", From: undefined };
}

export const UnreadRequest = {
  encode(message: UnreadRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.RecipientID !== "") {
      writer.uint32(10).string(message.RecipientID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    if (message.From !== undefined) {
      writer.uint32(24).int64(message.From);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UnreadRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnreadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.RecipientID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.From = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UnreadRequest {
    return {
      RecipientID: isSet(object.RecipientID) ? globalThis.String(object.RecipientID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      From: isSet(object.From) ? globalThis.Number(object.From) : undefined,
    };
  },

  toJSON(message: UnreadRequest): unknown {
    const obj: any = {};
    if (message.RecipientID !== "") {
      obj.RecipientID = message.RecipientID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.From !== undefined) {
      obj.From = Math.round(message.From);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UnreadRequest>, I>>(base?: I): UnreadRequest {
    return UnreadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UnreadRequest>, I>>(object: I): UnreadRequest {
    const message = createBaseUnreadRequest();
    message.RecipientID = object.RecipientID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    message.From = object.From ?? undefined;
    return message;
  },
};

function createBaseListRequest(): ListRequest {
  return { RecipientID: undefined, NotificationID: 0, OrganizationID: undefined, From: undefined };
}

export const ListRequest = {
  encode(message: ListRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.RecipientID !== undefined) {
      writer.uint32(10).string(message.RecipientID);
    }
    if (message.NotificationID !== 0) {
      writer.uint32(16).int64(message.NotificationID);
    }
    if (message.OrganizationID !== undefined) {
      writer.uint32(26).string(message.OrganizationID);
    }
    if (message.From !== undefined) {
      writer.uint32(32).int64(message.From);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.RecipientID = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.NotificationID = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.From = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListRequest {
    return {
      RecipientID: isSet(object.RecipientID) ? globalThis.String(object.RecipientID) : undefined,
      NotificationID: isSet(object.NotificationID) ? globalThis.Number(object.NotificationID) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : undefined,
      From: isSet(object.From) ? globalThis.Number(object.From) : undefined,
    };
  },

  toJSON(message: ListRequest): unknown {
    const obj: any = {};
    if (message.RecipientID !== undefined) {
      obj.RecipientID = message.RecipientID;
    }
    if (message.NotificationID !== 0) {
      obj.NotificationID = Math.round(message.NotificationID);
    }
    if (message.OrganizationID !== undefined) {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.From !== undefined) {
      obj.From = Math.round(message.From);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListRequest>, I>>(base?: I): ListRequest {
    return ListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListRequest>, I>>(object: I): ListRequest {
    const message = createBaseListRequest();
    message.RecipientID = object.RecipientID ?? undefined;
    message.NotificationID = object.NotificationID ?? 0;
    message.OrganizationID = object.OrganizationID ?? undefined;
    message.From = object.From ?? undefined;
    return message;
  },
};

function createBaseReadRequest(): ReadRequest {
  return { RecipientID: "", Key: [], OrganizationID: "" };
}

export const ReadRequest = {
  encode(message: ReadRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.RecipientID !== "") {
      writer.uint32(10).string(message.RecipientID);
    }
    for (const v of message.Key) {
      writer.uint32(18).string(v!);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(26).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReadRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.RecipientID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Key.push(reader.string());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadRequest {
    return {
      RecipientID: isSet(object.RecipientID) ? globalThis.String(object.RecipientID) : "",
      Key: globalThis.Array.isArray(object?.Key) ? object.Key.map((e: any) => globalThis.String(e)) : [],
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
    };
  },

  toJSON(message: ReadRequest): unknown {
    const obj: any = {};
    if (message.RecipientID !== "") {
      obj.RecipientID = message.RecipientID;
    }
    if (message.Key?.length) {
      obj.Key = message.Key;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadRequest>, I>>(base?: I): ReadRequest {
    return ReadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadRequest>, I>>(object: I): ReadRequest {
    const message = createBaseReadRequest();
    message.RecipientID = object.RecipientID ?? "";
    message.Key = object.Key?.map((e) => e) || [];
    message.OrganizationID = object.OrganizationID ?? "";
    return message;
  },
};

function createBaseReadAllRequest(): ReadAllRequest {
  return { RecipientID: "", OrganizationID: "" };
}

export const ReadAllRequest = {
  encode(message: ReadAllRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.RecipientID !== "") {
      writer.uint32(10).string(message.RecipientID);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(18).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ReadAllRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadAllRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.RecipientID = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadAllRequest {
    return {
      RecipientID: isSet(object.RecipientID) ? globalThis.String(object.RecipientID) : "",
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
    };
  },

  toJSON(message: ReadAllRequest): unknown {
    const obj: any = {};
    if (message.RecipientID !== "") {
      obj.RecipientID = message.RecipientID;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadAllRequest>, I>>(base?: I): ReadAllRequest {
    return ReadAllRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadAllRequest>, I>>(object: I): ReadAllRequest {
    const message = createBaseReadAllRequest();
    message.RecipientID = object.RecipientID ?? "";
    message.OrganizationID = object.OrganizationID ?? "";
    return message;
  },
};

function createBaseKey(): Key {
  return { Key: "" };
}

export const Key = {
  encode(message: Key, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== "") {
      writer.uint32(10).string(message.Key);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Key {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Key {
    return { Key: isSet(object.Key) ? globalThis.String(object.Key) : "" };
  },

  toJSON(message: Key): unknown {
    const obj: any = {};
    if (message.Key !== "") {
      obj.Key = message.Key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Key>, I>>(base?: I): Key {
    return Key.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Key>, I>>(object: I): Key {
    const message = createBaseKey();
    message.Key = object.Key ?? "";
    return message;
  },
};

export type NotificationServiceService = typeof NotificationServiceService;
export const NotificationServiceService = {
  /** Retrieval */
  top: {
    path: "/notification.NotificationService/Top",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: TopRequest) => Buffer.from(TopRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => TopRequest.decode(value),
    responseSerialize: (value: Notifications) => Buffer.from(Notifications.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Notifications.decode(value),
  },
  unread: {
    path: "/notification.NotificationService/Unread",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UnreadRequest) => Buffer.from(UnreadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UnreadRequest.decode(value),
    responseSerialize: (value: UnreadResponse) => Buffer.from(UnreadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UnreadResponse.decode(value),
  },
  list: {
    path: "/notification.NotificationService/List",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListRequest) => Buffer.from(ListRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ListRequest.decode(value),
    responseSerialize: (value: Notifications) => Buffer.from(Notifications.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Notifications.decode(value),
  },
  /** Updates */
  read: {
    path: "/notification.NotificationService/Read",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ReadRequest) => Buffer.from(ReadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ReadRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  readAll: {
    path: "/notification.NotificationService/ReadAll",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ReadAllRequest) => Buffer.from(ReadAllRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ReadAllRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /**
   * Message persistence endpoint
   * Checks if message exists, if not, persists it
   */
  persist: {
    path: "/notification.NotificationService/Persist",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Notification) => Buffer.from(Notification.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Notification.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Control */
  exists: {
    path: "/notification.NotificationService/Exists",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Key) => Buffer.from(Key.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Key.decode(value),
    responseSerialize: (value: Exist) => Buffer.from(Exist.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Exist.decode(value),
  },
} as const;

export interface NotificationServiceServer extends UntypedServiceImplementation {
  /** Retrieval */
  top: handleUnaryCall<TopRequest, Notifications>;
  unread: handleUnaryCall<UnreadRequest, UnreadResponse>;
  list: handleUnaryCall<ListRequest, Notifications>;
  /** Updates */
  read: handleUnaryCall<ReadRequest, Empty>;
  readAll: handleUnaryCall<ReadAllRequest, Empty>;
  /**
   * Message persistence endpoint
   * Checks if message exists, if not, persists it
   */
  persist: handleUnaryCall<Notification, Empty>;
  /** Control */
  exists: handleUnaryCall<Key, Exist>;
}

export interface NotificationServiceClient extends Client {
  /** Retrieval */
  top(request: TopRequest, callback: (error: ServiceError | null, response: Notifications) => void): ClientUnaryCall;
  top(
    request: TopRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Notifications) => void,
  ): ClientUnaryCall;
  top(
    request: TopRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Notifications) => void,
  ): ClientUnaryCall;
  unread(
    request: UnreadRequest,
    callback: (error: ServiceError | null, response: UnreadResponse) => void,
  ): ClientUnaryCall;
  unread(
    request: UnreadRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UnreadResponse) => void,
  ): ClientUnaryCall;
  unread(
    request: UnreadRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UnreadResponse) => void,
  ): ClientUnaryCall;
  list(request: ListRequest, callback: (error: ServiceError | null, response: Notifications) => void): ClientUnaryCall;
  list(
    request: ListRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Notifications) => void,
  ): ClientUnaryCall;
  list(
    request: ListRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Notifications) => void,
  ): ClientUnaryCall;
  /** Updates */
  read(request: ReadRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  read(
    request: ReadRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  read(
    request: ReadRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  readAll(request: ReadAllRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  readAll(
    request: ReadAllRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  readAll(
    request: ReadAllRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /**
   * Message persistence endpoint
   * Checks if message exists, if not, persists it
   */
  persist(request: Notification, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  persist(
    request: Notification,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  persist(
    request: Notification,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Control */
  exists(request: Key, callback: (error: ServiceError | null, response: Exist) => void): ClientUnaryCall;
  exists(
    request: Key,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Exist) => void,
  ): ClientUnaryCall;
  exists(
    request: Key,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Exist) => void,
  ): ClientUnaryCall;
}

export const NotificationServiceClient = makeGenericClientConstructor(
  NotificationServiceService,
  "notification.NotificationService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): NotificationServiceClient;
  service: typeof NotificationServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
