syntax = "proto3";

package notification;

option go_package = "./notification";

import "google/protobuf/Empty.proto";
import "types/types.proto";
import "notification.proto";

service NotificationService {
    // Retrieval
    rpc Top(TopRequest) returns (Notifications) {}
    rpc Unread(UnreadRequest) returns (UnreadResponse) {}
    rpc List(ListRequest) returns (Notifications) {}

    // Updates
    rpc Read(ReadRequest) returns (google.protobuf.Empty) {}
    rpc ReadAll(ReadAllRequest) returns (google.protobuf.Empty) {}

    // Message persistence endpoint
    // Checks if message exists, if not, persists it
    rpc Persist(Notification) returns (google.protobuf.Empty) {}

    // Control
    rpc Exists(Key) returns (Exist) {}
}

message TopRequest {
    string RecipientID = 1;
    repeated notification.types.NotificationType Type = 2;
    optional string OrganizationID = 3;
}

message UnreadRequest {
    string RecipientID = 1;
}

// ListRequest defines the filters for fetching notifications:
//  - if neither OrganizationID nor RecipientID is provided, the request is for syste-wide notifications (sologenic_admin notifications)
//  - if only OrganizationID is provided, the request is for an organization's notifications + system-wide notifications
//  - if both OrganizationID and RecipientID are provided, the request is for an individual user's notifications + user's organization notifications + system-wide notifications
message ListRequest {
    optional string RecipientID = 1;
    int64 NotificationID = 2;
    optional string OrganizationID = 3;
}

message ReadRequest {
    string RecipientID = 1;
    repeated string Key = 2;
}

message ReadAllRequest {
    string RecipientID = 1;
}

message Key {
    string Key = 1;
}
