// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.6
// source: notification-grpc.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_Top_FullMethodName     = "/notification.NotificationService/Top"
	NotificationService_Unread_FullMethodName  = "/notification.NotificationService/Unread"
	NotificationService_List_FullMethodName    = "/notification.NotificationService/List"
	NotificationService_Read_FullMethodName    = "/notification.NotificationService/Read"
	NotificationService_ReadAll_FullMethodName = "/notification.NotificationService/ReadAll"
	NotificationService_Persist_FullMethodName = "/notification.NotificationService/Persist"
	NotificationService_Exists_FullMethodName  = "/notification.NotificationService/Exists"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	// Retrieval
	Top(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*Notifications, error)
	Unread(ctx context.Context, in *UnreadRequest, opts ...grpc.CallOption) (*UnreadResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Notifications, error)
	// Updates
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Message persistence endpoint
	// Checks if message exists, if not, persists it
	Persist(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Control
	Exists(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Exist, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) Top(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*Notifications, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notifications)
	err := c.cc.Invoke(ctx, NotificationService_Top_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Unread(ctx context.Context, in *UnreadRequest, opts ...grpc.CallOption) (*UnreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnreadResponse)
	err := c.cc.Invoke(ctx, NotificationService_Unread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Notifications, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notifications)
	err := c.cc.Invoke(ctx, NotificationService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_ReadAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Persist(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_Persist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Exists(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Exist, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exist)
	err := c.cc.Invoke(ctx, NotificationService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations should embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	// Retrieval
	Top(context.Context, *TopRequest) (*Notifications, error)
	Unread(context.Context, *UnreadRequest) (*UnreadResponse, error)
	List(context.Context, *ListRequest) (*Notifications, error)
	// Updates
	Read(context.Context, *ReadRequest) (*emptypb.Empty, error)
	ReadAll(context.Context, *ReadAllRequest) (*emptypb.Empty, error)
	// Message persistence endpoint
	// Checks if message exists, if not, persists it
	Persist(context.Context, *Notification) (*emptypb.Empty, error)
	// Control
	Exists(context.Context, *Key) (*Exist, error)
}

// UnimplementedNotificationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) Top(context.Context, *TopRequest) (*Notifications, error) {
	return nil, status.Error(codes.Unimplemented, "method Top not implemented")
}
func (UnimplementedNotificationServiceServer) Unread(context.Context, *UnreadRequest) (*UnreadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unread not implemented")
}
func (UnimplementedNotificationServiceServer) List(context.Context, *ListRequest) (*Notifications, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNotificationServiceServer) Read(context.Context, *ReadRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedNotificationServiceServer) ReadAll(context.Context, *ReadAllRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAll not implemented")
}
func (UnimplementedNotificationServiceServer) Persist(context.Context, *Notification) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Persist not implemented")
}
func (UnimplementedNotificationServiceServer) Exists(context.Context, *Key) (*Exist, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_Top_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Top(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Top_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Top(ctx, req.(*TopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Unread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Unread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Unread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Unread(ctx, req.(*UnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ReadAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Persist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Persist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Persist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Persist(ctx, req.(*Notification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Exists(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Top",
			Handler:    _NotificationService_Top_Handler,
		},
		{
			MethodName: "Unread",
			Handler:    _NotificationService_Unread_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NotificationService_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _NotificationService_Read_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _NotificationService_ReadAll_Handler,
		},
		{
			MethodName: "Persist",
			Handler:    _NotificationService_Persist_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _NotificationService_Exists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification-grpc.proto",
}
