// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: notification.proto

package notification

import (
	formats "github.com/sologenic/com-fs-notification-model/formats"
	parameters "github.com/sologenic/com-fs-notification-model/parameters"
	types "github.com/sologenic/com-fs-notification-model/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Importance int32

const (
	Importance_NOT_USED1 Importance = 0 // Need unique enum values for proto (C requirement, we don't use C)
	Importance_NORMAL    Importance = 1
	Importance_IMPORTANT Importance = 2
	Importance_CRITICAL  Importance = 3
)

// Enum value maps for Importance.
var (
	Importance_name = map[int32]string{
		0: "NOT_USED1",
		1: "NORMAL",
		2: "IMPORTANT",
		3: "CRITICAL",
	}
	Importance_value = map[string]int32{
		"NOT_USED1": 0,
		"NORMAL":    1,
		"IMPORTANT": 2,
		"CRITICAL":  3,
	}
)

func (x Importance) Enum() *Importance {
	p := new(Importance)
	*p = x
	return p
}

func (x Importance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Importance) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (Importance) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x Importance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Importance.Descriptor instead.
func (Importance) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type Exist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=Exists,proto3" json:"Exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exist) Reset() {
	*x = Exist{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exist) ProtoMessage() {}

func (x *Exist) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exist.ProtoReflect.Descriptor instead.
func (*Exist) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Exist) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasUnread     bool                   `protobuf:"varint,1,opt,name=HasUnread,proto3" json:"HasUnread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadResponse) Reset() {
	*x = UnreadResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadResponse) ProtoMessage() {}

func (x *UnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadResponse.ProtoReflect.Descriptor instead.
func (*UnreadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *UnreadResponse) GetHasUnread() bool {
	if x != nil {
		return x.HasUnread
	}
	return false
}

type Notifications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  []*Notification        `protobuf:"bytes,1,rep,name=Notification,proto3" json:"Notification,omitempty"`
	More          *More                  `protobuf:"bytes,2,opt,name=More,proto3" json:"More,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notifications) Reset() {
	*x = Notifications{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notifications) ProtoMessage() {}

func (x *Notifications) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notifications.ProtoReflect.Descriptor instead.
func (*Notifications) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Notifications) GetNotification() []*Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *Notifications) GetMore() *More {
	if x != nil {
		return x.More
	}
	return nil
}

type More struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TS            int64                  `protobuf:"varint,2,opt,name=TS,proto3" json:"TS,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *More) Reset() {
	*x = More{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *More) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*More) ProtoMessage() {}

func (x *More) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use More.ProtoReflect.Descriptor instead.
func (*More) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *More) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *More) GetTS() int64 {
	if x != nil {
		return x.TS
	}
	return 0
}

// Notifications can be high level: Give me NFT Like notifications on my NFTs, or low level: Let me know when collection XYZ is updated
// The absence or presence of the ID field determines the level of notification
type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                         // Has a meaning if combined with the Type
	RecipientID    *string                `protobuf:"bytes,2,opt,name=RecipientID,proto3,oneof" json:"RecipientID,omitempty"` // Recipient is either a user or an admin
	Type           types.NotificationType `protobuf:"varint,3,opt,name=Type,proto3,enum=notification.types.NotificationType" json:"Type,omitempty"`
	Message        *Message               `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	NotificationID int64                  `protobuf:"varint,8,opt,name=NotificationID,proto3" json:"NotificationID,omitempty"`                             // Unique ID used for Read notifications matching. Timestamp in nanos assigned by the storage layer
	Read           bool                   `protobuf:"varint,9,opt,name=Read,proto3" json:"Read,omitempty"`                                                 // Default false. Used for personal messages read state, merged with Read state from message Read
	From           string                 `protobuf:"bytes,10,opt,name=From,proto3" json:"From,omitempty"`                                                 // AccountID of the sender of the message (if applicable)
	Importance     Importance             `protobuf:"varint,11,opt,name=Importance,proto3,enum=notification.Importance" json:"Importance,omitempty"`       // Default Normal
	Target         []parameters.Target    `protobuf:"varint,12,rep,packed,name=Target,proto3,enum=notification.parameters.Target" json:"Target,omitempty"` // Default none
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`                                       // Default none, used for admin/system/marketing notifications so those can be filtered
	ValidFrom      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=ValidFrom,proto3" json:"ValidFrom,omitempty"`                                       // Default none, used for admin/system/marketing notifications so those can be filtered
	Key            string                 `protobuf:"bytes,15,opt,name=Key,proto3" json:"Key,omitempty"`                                                   // Unique sender generated stable key (prevents duplicate notifications)
	OrganizationID *string                `protobuf:"bytes,16,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`                       // Only the sologenic admin can create notifications with no organization ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *Notification) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Notification) GetRecipientID() string {
	if x != nil && x.RecipientID != nil {
		return *x.RecipientID
	}
	return ""
}

func (x *Notification) GetType() types.NotificationType {
	if x != nil {
		return x.Type
	}
	return types.NotificationType(0)
}

func (x *Notification) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Notification) GetNotificationID() int64 {
	if x != nil {
		return x.NotificationID
	}
	return 0
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Notification) GetImportance() Importance {
	if x != nil {
		return x.Importance
	}
	return Importance_NOT_USED1
}

func (x *Notification) GetTarget() []parameters.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Notification) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Notification) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Notification) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Notification) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Format        formats.Format          `protobuf:"varint,1,opt,name=Format,proto3,enum=notification.formats.Format" json:"Format,omitempty"`
	Subject       string                  `protobuf:"bytes,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Body          string                  `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	Parameter     []*parameters.Parameter `protobuf:"bytes,4,rep,name=Parameter,proto3" json:"Parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetFormat() formats.Format {
	if x != nil {
		return x.Format
	}
	return formats.Format(0)
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Message) GetParameter() []*parameters.Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11types/types.proto\x1a\x1bparameters/parameters.proto\x1a\x15formats/formats.proto\"\x1f\n" +
	"\x05Exist\x12\x16\n" +
	"\x06Exists\x18\x01 \x01(\bR\x06Exists\".\n" +
	"\x0eUnreadResponse\x12\x1c\n" +
	"\tHasUnread\x18\x01 \x01(\bR\tHasUnread\"w\n" +
	"\rNotifications\x12>\n" +
	"\fNotification\x18\x01 \x03(\v2\x1a.notification.NotificationR\fNotification\x12&\n" +
	"\x04More\x18\x02 \x01(\v2\x12.notification.MoreR\x04More\"&\n" +
	"\x04More\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x0e\n" +
	"\x02TS\x18\x02 \x01(\x03R\x02TS\"\xbd\x05\n" +
	"\fNotification\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12%\n" +
	"\vRecipientID\x18\x02 \x01(\tH\x00R\vRecipientID\x88\x01\x01\x128\n" +
	"\x04Type\x18\x03 \x01(\x0e2$.notification.types.NotificationTypeR\x04Type\x12/\n" +
	"\aMessage\x18\x04 \x01(\v2\x15.notification.MessageR\aMessage\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12&\n" +
	"\x0eNotificationID\x18\b \x01(\x03R\x0eNotificationID\x12\x12\n" +
	"\x04Read\x18\t \x01(\bR\x04Read\x12\x12\n" +
	"\x04From\x18\n" +
	" \x01(\tR\x04From\x128\n" +
	"\n" +
	"Importance\x18\v \x01(\x0e2\x18.notification.ImportanceR\n" +
	"Importance\x127\n" +
	"\x06Target\x18\f \x03(\x0e2\x1f.notification.parameters.TargetR\x06Target\x128\n" +
	"\tExpiresAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tExpiresAt\x128\n" +
	"\tValidFrom\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tValidFrom\x12\x10\n" +
	"\x03Key\x18\x0f \x01(\tR\x03Key\x12+\n" +
	"\x0eOrganizationID\x18\x10 \x01(\tH\x01R\x0eOrganizationID\x88\x01\x01B\x0e\n" +
	"\f_RecipientIDB\x11\n" +
	"\x0f_OrganizationID\"\xaf\x01\n" +
	"\aMessage\x124\n" +
	"\x06Format\x18\x01 \x01(\x0e2\x1c.notification.formats.FormatR\x06Format\x12\x18\n" +
	"\aSubject\x18\x02 \x01(\tR\aSubject\x12\x12\n" +
	"\x04Body\x18\x03 \x01(\tR\x04Body\x12@\n" +
	"\tParameter\x18\x04 \x03(\v2\".notification.parameters.ParameterR\tParameter*D\n" +
	"\n" +
	"Importance\x12\r\n" +
	"\tNOT_USED1\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\r\n" +
	"\tIMPORTANT\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03B\x10Z\x0e./notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notification_proto_goTypes = []any{
	(Importance)(0),               // 0: notification.Importance
	(*Exist)(nil),                 // 1: notification.Exist
	(*UnreadResponse)(nil),        // 2: notification.UnreadResponse
	(*Notifications)(nil),         // 3: notification.Notifications
	(*More)(nil),                  // 4: notification.More
	(*Notification)(nil),          // 5: notification.Notification
	(*Message)(nil),               // 6: notification.Message
	(types.NotificationType)(0),   // 7: notification.types.NotificationType
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(parameters.Target)(0),        // 9: notification.parameters.Target
	(formats.Format)(0),           // 10: notification.formats.Format
	(*parameters.Parameter)(nil),  // 11: notification.parameters.Parameter
}
var file_notification_proto_depIdxs = []int32{
	5,  // 0: notification.Notifications.Notification:type_name -> notification.Notification
	4,  // 1: notification.Notifications.More:type_name -> notification.More
	7,  // 2: notification.Notification.Type:type_name -> notification.types.NotificationType
	6,  // 3: notification.Notification.Message:type_name -> notification.Message
	8,  // 4: notification.Notification.CreatedAt:type_name -> google.protobuf.Timestamp
	8,  // 5: notification.Notification.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 6: notification.Notification.Importance:type_name -> notification.Importance
	9,  // 7: notification.Notification.Target:type_name -> notification.parameters.Target
	8,  // 8: notification.Notification.ExpiresAt:type_name -> google.protobuf.Timestamp
	8,  // 9: notification.Notification.ValidFrom:type_name -> google.protobuf.Timestamp
	10, // 10: notification.Message.Format:type_name -> notification.formats.Format
	11, // 11: notification.Message.Parameter:type_name -> notification.parameters.Parameter
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	file_notification_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
