// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: notification-grpc.proto

package notification

import (
	types "github.com/sologenic/com-fs-notification-model/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	RecipientID    string                   `protobuf:"bytes,1,opt,name=RecipientID,proto3" json:"RecipientID,omitempty"`
	Type           []types.NotificationType `protobuf:"varint,2,rep,packed,name=Type,proto3,enum=notification.types.NotificationType" json:"Type,omitempty"`
	OrganizationID *string                  `protobuf:"bytes,3,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	// Used to fetch notifications for a user: fetching broadcast type notifications should be relative to when the user was created.
	From          *int64 `protobuf:"varint,4,opt,name=From,proto3,oneof" json:"From,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRequest) Reset() {
	*x = TopRequest{}
	mi := &file_notification_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRequest) ProtoMessage() {}

func (x *TopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRequest.ProtoReflect.Descriptor instead.
func (*TopRequest) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *TopRequest) GetRecipientID() string {
	if x != nil {
		return x.RecipientID
	}
	return ""
}

func (x *TopRequest) GetType() []types.NotificationType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TopRequest) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *TopRequest) GetFrom() int64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

type UnreadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientID    string                 `protobuf:"bytes,1,opt,name=RecipientID,proto3" json:"RecipientID,omitempty"`
	OrganizationID string                 `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	// Used to fetch notifications for a user: fetching broadcast type notifications should be relative to when the user was created.
	From          *int64 `protobuf:"varint,3,opt,name=From,proto3,oneof" json:"From,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadRequest) Reset() {
	*x = UnreadRequest{}
	mi := &file_notification_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadRequest) ProtoMessage() {}

func (x *UnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadRequest.ProtoReflect.Descriptor instead.
func (*UnreadRequest) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *UnreadRequest) GetRecipientID() string {
	if x != nil {
		return x.RecipientID
	}
	return ""
}

func (x *UnreadRequest) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *UnreadRequest) GetFrom() int64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

// ListRequest defines the filters for fetching notifications:
//   - if neither OrganizationID nor RecipientID is provided, the request is for syste-wide notifications (sologenic_admin notifications)
//   - if only OrganizationID is provided, the request is for an organization's notifications + system-wide notifications
//   - if both OrganizationID and RecipientID are provided, the request is for an individual user's notifications + user's organization notifications + system-wide notifications
type ListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientID    *string                `protobuf:"bytes,1,opt,name=RecipientID,proto3,oneof" json:"RecipientID,omitempty"`
	NotificationID int64                  `protobuf:"varint,2,opt,name=NotificationID,proto3" json:"NotificationID,omitempty"`
	OrganizationID *string                `protobuf:"bytes,3,opt,name=OrganizationID,proto3,oneof" json:"OrganizationID,omitempty"`
	// Used to fetch notifications for a user: fetching broadcast type notifications should be relative to when the user was created.
	From          *int64 `protobuf:"varint,4,opt,name=From,proto3,oneof" json:"From,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_notification_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetRecipientID() string {
	if x != nil && x.RecipientID != nil {
		return *x.RecipientID
	}
	return ""
}

func (x *ListRequest) GetNotificationID() int64 {
	if x != nil {
		return x.NotificationID
	}
	return 0
}

func (x *ListRequest) GetOrganizationID() string {
	if x != nil && x.OrganizationID != nil {
		return *x.OrganizationID
	}
	return ""
}

func (x *ListRequest) GetFrom() int64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

type ReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientID    string                 `protobuf:"bytes,1,opt,name=RecipientID,proto3" json:"RecipientID,omitempty"`
	Key            []string               `protobuf:"bytes,2,rep,name=Key,proto3" json:"Key,omitempty"`
	OrganizationID string                 `protobuf:"bytes,3,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_notification_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetRecipientID() string {
	if x != nil {
		return x.RecipientID
	}
	return ""
}

func (x *ReadRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReadRequest) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

type ReadAllRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientID    string                 `protobuf:"bytes,1,opt,name=RecipientID,proto3" json:"RecipientID,omitempty"`
	OrganizationID string                 `protobuf:"bytes,2,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadAllRequest) Reset() {
	*x = ReadAllRequest{}
	mi := &file_notification_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllRequest) ProtoMessage() {}

func (x *ReadAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllRequest.ProtoReflect.Descriptor instead.
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAllRequest) GetRecipientID() string {
	if x != nil {
		return x.RecipientID
	}
	return ""
}

func (x *ReadAllRequest) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_notification_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_notification_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_notification_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_notification_grpc_proto protoreflect.FileDescriptor

const file_notification_grpc_proto_rawDesc = "" +
	"\n" +
	"\x17notification-grpc.proto\x12\fnotification\x1a\x1bgoogle/protobuf/Empty.proto\x1a\x11types/types.proto\x1a\x12notification.proto\"\xca\x01\n" +
	"\n" +
	"TopRequest\x12 \n" +
	"\vRecipientID\x18\x01 \x01(\tR\vRecipientID\x128\n" +
	"\x04Type\x18\x02 \x03(\x0e2$.notification.types.NotificationTypeR\x04Type\x12+\n" +
	"\x0eOrganizationID\x18\x03 \x01(\tH\x00R\x0eOrganizationID\x88\x01\x01\x12\x17\n" +
	"\x04From\x18\x04 \x01(\x03H\x01R\x04From\x88\x01\x01B\x11\n" +
	"\x0f_OrganizationIDB\a\n" +
	"\x05_From\"{\n" +
	"\rUnreadRequest\x12 \n" +
	"\vRecipientID\x18\x01 \x01(\tR\vRecipientID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID\x12\x17\n" +
	"\x04From\x18\x03 \x01(\x03H\x00R\x04From\x88\x01\x01B\a\n" +
	"\x05_From\"\xce\x01\n" +
	"\vListRequest\x12%\n" +
	"\vRecipientID\x18\x01 \x01(\tH\x00R\vRecipientID\x88\x01\x01\x12&\n" +
	"\x0eNotificationID\x18\x02 \x01(\x03R\x0eNotificationID\x12+\n" +
	"\x0eOrganizationID\x18\x03 \x01(\tH\x01R\x0eOrganizationID\x88\x01\x01\x12\x17\n" +
	"\x04From\x18\x04 \x01(\x03H\x02R\x04From\x88\x01\x01B\x0e\n" +
	"\f_RecipientIDB\x11\n" +
	"\x0f_OrganizationIDB\a\n" +
	"\x05_From\"i\n" +
	"\vReadRequest\x12 \n" +
	"\vRecipientID\x18\x01 \x01(\tR\vRecipientID\x12\x10\n" +
	"\x03Key\x18\x02 \x03(\tR\x03Key\x12&\n" +
	"\x0eOrganizationID\x18\x03 \x01(\tR\x0eOrganizationID\"Z\n" +
	"\x0eReadAllRequest\x12 \n" +
	"\vRecipientID\x18\x01 \x01(\tR\vRecipientID\x12&\n" +
	"\x0eOrganizationID\x18\x02 \x01(\tR\x0eOrganizationID\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key2\xd3\x03\n" +
	"\x13NotificationService\x12>\n" +
	"\x03Top\x12\x18.notification.TopRequest\x1a\x1b.notification.Notifications\"\x00\x12E\n" +
	"\x06Unread\x12\x1b.notification.UnreadRequest\x1a\x1c.notification.UnreadResponse\"\x00\x12@\n" +
	"\x04List\x12\x19.notification.ListRequest\x1a\x1b.notification.Notifications\"\x00\x12;\n" +
	"\x04Read\x12\x19.notification.ReadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\aReadAll\x12\x1c.notification.ReadAllRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\aPersist\x12\x1a.notification.Notification\x1a\x16.google.protobuf.Empty\"\x00\x122\n" +
	"\x06Exists\x12\x11.notification.Key\x1a\x13.notification.Exist\"\x00B\x10Z\x0e./notificationb\x06proto3"

var (
	file_notification_grpc_proto_rawDescOnce sync.Once
	file_notification_grpc_proto_rawDescData []byte
)

func file_notification_grpc_proto_rawDescGZIP() []byte {
	file_notification_grpc_proto_rawDescOnce.Do(func() {
		file_notification_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_grpc_proto_rawDesc), len(file_notification_grpc_proto_rawDesc)))
	})
	return file_notification_grpc_proto_rawDescData
}

var file_notification_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notification_grpc_proto_goTypes = []any{
	(*TopRequest)(nil),          // 0: notification.TopRequest
	(*UnreadRequest)(nil),       // 1: notification.UnreadRequest
	(*ListRequest)(nil),         // 2: notification.ListRequest
	(*ReadRequest)(nil),         // 3: notification.ReadRequest
	(*ReadAllRequest)(nil),      // 4: notification.ReadAllRequest
	(*Key)(nil),                 // 5: notification.Key
	(types.NotificationType)(0), // 6: notification.types.NotificationType
	(*Notification)(nil),        // 7: notification.Notification
	(*Notifications)(nil),       // 8: notification.Notifications
	(*UnreadResponse)(nil),      // 9: notification.UnreadResponse
	(*emptypb.Empty)(nil),       // 10: google.protobuf.Empty
	(*Exist)(nil),               // 11: notification.Exist
}
var file_notification_grpc_proto_depIdxs = []int32{
	6,  // 0: notification.TopRequest.Type:type_name -> notification.types.NotificationType
	0,  // 1: notification.NotificationService.Top:input_type -> notification.TopRequest
	1,  // 2: notification.NotificationService.Unread:input_type -> notification.UnreadRequest
	2,  // 3: notification.NotificationService.List:input_type -> notification.ListRequest
	3,  // 4: notification.NotificationService.Read:input_type -> notification.ReadRequest
	4,  // 5: notification.NotificationService.ReadAll:input_type -> notification.ReadAllRequest
	7,  // 6: notification.NotificationService.Persist:input_type -> notification.Notification
	5,  // 7: notification.NotificationService.Exists:input_type -> notification.Key
	8,  // 8: notification.NotificationService.Top:output_type -> notification.Notifications
	9,  // 9: notification.NotificationService.Unread:output_type -> notification.UnreadResponse
	8,  // 10: notification.NotificationService.List:output_type -> notification.Notifications
	10, // 11: notification.NotificationService.Read:output_type -> google.protobuf.Empty
	10, // 12: notification.NotificationService.ReadAll:output_type -> google.protobuf.Empty
	10, // 13: notification.NotificationService.Persist:output_type -> google.protobuf.Empty
	11, // 14: notification.NotificationService.Exists:output_type -> notification.Exist
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_notification_grpc_proto_init() }
func file_notification_grpc_proto_init() {
	if File_notification_grpc_proto != nil {
		return
	}
	file_notification_proto_init()
	file_notification_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_notification_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	file_notification_grpc_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_grpc_proto_rawDesc), len(file_notification_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_grpc_proto_goTypes,
		DependencyIndexes: file_notification_grpc_proto_depIdxs,
		MessageInfos:      file_notification_grpc_proto_msgTypes,
	}.Build()
	File_notification_grpc_proto = out.File
	file_notification_grpc_proto_goTypes = nil
	file_notification_grpc_proto_depIdxs = nil
}
