syntax = "proto3";

package notification.types;

option go_package = "github.com/sologenic/com-fs-notification-model/types";

// Do not RENUMBER notification types, they are used in the database as enum int values
// You will destroy the existing messages and destroy all history if you do so
enum NotificationType {
    NOT_USED = 0; // Need unique enum values for proto (C requirement, we don't use C)
    Maintenance = 1;
    Admin = 2;
    Marketing = 3;
    IndividualMessage = 4;
    AccountBanned = 5;
    AccountVerified = 6;
    KYC = 7;
    NewOrganization = 8;
}
