// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Do not RENUMBER notification types, they are used in the database as enum int values
// You will destroy the existing messages and destroy all history if you do so
type NotificationType int32

const (
	NotificationType_NOT_USED          NotificationType = 0 // Need unique enum values for proto (C requirement, we don't use C)
	NotificationType_Maintenance       NotificationType = 1
	NotificationType_Admin             NotificationType = 2
	NotificationType_Marketing         NotificationType = 3
	NotificationType_IndividualMessage NotificationType = 4
	NotificationType_Account           NotificationType = 5
	NotificationType_User              NotificationType = 6
	NotificationType_KYC               NotificationType = 7
	NotificationType_Organization      NotificationType = 8
	NotificationType_SupportTicket     NotificationType = 9
	NotificationType_Document          NotificationType = 10
	NotificationType_Partner           NotificationType = 11
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOT_USED",
		1:  "Maintenance",
		2:  "Admin",
		3:  "Marketing",
		4:  "IndividualMessage",
		5:  "Account",
		6:  "User",
		7:  "KYC",
		8:  "Organization",
		9:  "SupportTicket",
		10: "Document",
		11: "Partner",
	}
	NotificationType_value = map[string]int32{
		"NOT_USED":          0,
		"Maintenance":       1,
		"Admin":             2,
		"Marketing":         3,
		"IndividualMessage": 4,
		"Account":           5,
		"User":              6,
		"KYC":               7,
		"Organization":      8,
		"SupportTicket":     9,
		"Document":          10,
		"Partner":           11,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_types_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_types_types_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_types_types_proto_rawDescGZIP(), []int{0}
}

var File_types_types_proto protoreflect.FileDescriptor

const file_types_types_proto_rawDesc = "" +
	"\n" +
	"\x11types/types.proto\x12\x12notification.types*\xc2\x01\n" +
	"\x10NotificationType\x12\f\n" +
	"\bNOT_USED\x10\x00\x12\x0f\n" +
	"\vMaintenance\x10\x01\x12\t\n" +
	"\x05Admin\x10\x02\x12\r\n" +
	"\tMarketing\x10\x03\x12\x15\n" +
	"\x11IndividualMessage\x10\x04\x12\v\n" +
	"\aAccount\x10\x05\x12\b\n" +
	"\x04User\x10\x06\x12\a\n" +
	"\x03KYC\x10\a\x12\x10\n" +
	"\fOrganization\x10\b\x12\x11\n" +
	"\rSupportTicket\x10\t\x12\f\n" +
	"\bDocument\x10\n" +
	"\x12\v\n" +
	"\aPartner\x10\vB6Z4github.com/sologenic/com-fs-notification-model/typesb\x06proto3"

var (
	file_types_types_proto_rawDescOnce sync.Once
	file_types_types_proto_rawDescData []byte
)

func file_types_types_proto_rawDescGZIP() []byte {
	file_types_types_proto_rawDescOnce.Do(func() {
		file_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)))
	})
	return file_types_types_proto_rawDescData
}

var file_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_types_proto_goTypes = []any{
	(NotificationType)(0), // 0: notification.types.NotificationType
}
var file_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_types_proto_init() }
func file_types_types_proto_init() {
	if File_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_types_proto_rawDesc), len(file_types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_types_proto_goTypes,
		DependencyIndexes: file_types_types_proto_depIdxs,
		EnumInfos:         file_types_types_proto_enumTypes,
	}.Build()
	File_types_types_proto = out.File
	file_types_types_proto_goTypes = nil
	file_types_types_proto_depIdxs = nil
}
