// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v5.29.1
// source: types/types.proto

/* eslint-disable */

export const protobufPackage = "notification.types";

/**
 * Do not RENUMBER notification types, they are used in the database as enum int values
 * You will destroy the existing messages and destroy all history if you do so
 */
export enum NotificationType {
  /** NOT_USED - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED = 0,
  Maintenance = 1,
  Admin = 2,
  Marketing = 3,
  IndividualMessage = 4,
  Account = 5,
  User = 6,
  KYC = 7,
  Organization = 8,
  SupportTicket = 9,
  UNRECOGNIZED = -1,
}

export function notificationTypeFromJSON(object: any): NotificationType {
  switch (object) {
    case 0:
    case "NOT_USED":
      return NotificationType.NOT_USED;
    case 1:
    case "Maintenance":
      return NotificationType.Maintenance;
    case 2:
    case "Admin":
      return NotificationType.Admin;
    case 3:
    case "Marketing":
      return NotificationType.Marketing;
    case 4:
    case "IndividualMessage":
      return NotificationType.IndividualMessage;
    case 5:
    case "Account":
      return NotificationType.Account;
    case 6:
    case "User":
      return NotificationType.User;
    case 7:
    case "KYC":
      return NotificationType.KYC;
    case 8:
    case "Organization":
      return NotificationType.Organization;
    case 9:
    case "SupportTicket":
      return NotificationType.SupportTicket;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NotificationType.UNRECOGNIZED;
  }
}

export function notificationTypeToJSON(object: NotificationType): string {
  switch (object) {
    case NotificationType.NOT_USED:
      return "NOT_USED";
    case NotificationType.Maintenance:
      return "Maintenance";
    case NotificationType.Admin:
      return "Admin";
    case NotificationType.Marketing:
      return "Marketing";
    case NotificationType.IndividualMessage:
      return "IndividualMessage";
    case NotificationType.Account:
      return "Account";
    case NotificationType.User:
      return "User";
    case NotificationType.KYC:
      return "KYC";
    case NotificationType.Organization:
      return "Organization";
    case NotificationType.SupportTicket:
      return "SupportTicket";
    case NotificationType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
