// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v4.24.3
// source: types/types.proto

/* eslint-disable */

export const protobufPackage = "notification.types";

/**
 * Do not RENUMBER notification types, they are used in the database as enum int values
 * You will destroy the existing messages and destroy all history if you do so
 */
export enum NotificationType {
  /** NOT_USED - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED = 0,
  Marketing = 1,
  IndividualMessage = 2,
  KYC = 3,
  Account = 4,
  Asset = 5,
  Admin = 6,
  UNRECOGNIZED = -1,
}

export function notificationTypeFromJSON(object: any): NotificationType {
  switch (object) {
    case 0:
    case "NOT_USED":
      return NotificationType.NOT_USED;
    case 1:
    case "Marketing":
      return NotificationType.Marketing;
    case 2:
    case "IndividualMessage":
      return NotificationType.IndividualMessage;
    case 3:
    case "KYC":
      return NotificationType.KYC;
    case 4:
    case "Account":
      return NotificationType.Account;
    case 5:
    case "Asset":
      return NotificationType.Asset;
    case 6:
    case "Admin":
      return NotificationType.Admin;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NotificationType.UNRECOGNIZED;
  }
}

export function notificationTypeToJSON(object: NotificationType): string {
  switch (object) {
    case NotificationType.NOT_USED:
      return "NOT_USED";
    case NotificationType.Marketing:
      return "Marketing";
    case NotificationType.IndividualMessage:
      return "IndividualMessage";
    case NotificationType.KYC:
      return "KYC";
    case NotificationType.Account:
      return "Account";
    case NotificationType.Asset:
      return "Asset";
    case NotificationType.Admin:
      return "Admin";
    case NotificationType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
