// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.1
// source: parameters/parameters.proto

package parameters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_NOT_USED7 SourceType = 0 // Need unique enum values for proto (C requirement, we don't use C)
	SourceType_ADDRESS   SourceType = 1
	SourceType_WALLET    SourceType = 2
	SourceType_KYC       SourceType = 3
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "NOT_USED7",
		1: "ADDRESS",
		2: "WALLET",
		3: "KYC",
	}
	SourceType_value = map[string]int32{
		"NOT_USED7": 0,
		"ADDRESS":   1,
		"WALLET":    2,
		"KYC":       3,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{0}
}

type Target int32

const (
	Target_NOT_USED8 Target = 0 // Need unique enum values for proto (C requirement, we don't use C)
	Target_FIREBASE  Target = 1
	Target_WEB       Target = 2
	Target_EMAIL     Target = 3
)

// Enum value maps for Target.
var (
	Target_name = map[int32]string{
		0: "NOT_USED8",
		1: "FIREBASE",
		2: "WEB",
		3: "EMAIL",
	}
	Target_value = map[string]int32{
		"NOT_USED8": 0,
		"FIREBASE":  1,
		"WEB":       2,
		"EMAIL":     3,
	}
)

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[1].Descriptor()
}

func (Target) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[1]
}

func (x Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target.Descriptor instead.
func (Target) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{1}
}

type ParameterLabel int32

const (
	ParameterLabel_NOT_USED3   ParameterLabel = 0 // Need unique enum values for proto (C requirement, we don't use C)
	ParameterLabel_DATETIME    ParameterLabel = 1
	ParameterLabel_AMOUNT      ParameterLabel = 2
	ParameterLabel_INITIATOR   ParameterLabel = 3
	ParameterLabel_DESTINATION ParameterLabel = 4
	ParameterLabel_ID          ParameterLabel = 5 // Generically usable ID field
	ParameterLabel_NAME        ParameterLabel = 6 // Generically usable NAME field
)

// Enum value maps for ParameterLabel.
var (
	ParameterLabel_name = map[int32]string{
		0: "NOT_USED3",
		1: "DATETIME",
		2: "AMOUNT",
		3: "INITIATOR",
		4: "DESTINATION",
		5: "ID",
		6: "NAME",
	}
	ParameterLabel_value = map[string]int32{
		"NOT_USED3":   0,
		"DATETIME":    1,
		"AMOUNT":      2,
		"INITIATOR":   3,
		"DESTINATION": 4,
		"ID":          5,
		"NAME":        6,
	}
)

func (x ParameterLabel) Enum() *ParameterLabel {
	p := new(ParameterLabel)
	*p = x
	return p
}

func (x ParameterLabel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParameterLabel) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[2].Descriptor()
}

func (ParameterLabel) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[2]
}

func (x ParameterLabel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParameterLabel.Descriptor instead.
func (ParameterLabel) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{2}
}

// Parameter types for DataEvaluation: Sadly enums have to be unique, and we want to use an enum here to limit input/settings
// on definition level and not on code level: PT_ is used in front of the parameter type to avoid conflicts
type DataType int32

const (
	DataType_NOT_USED4 DataType = 0 // Need unique enum values for proto (C requirement, we don't use C)
	DataType_STRING    DataType = 1
	DataType_NUMBER    DataType = 2
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "NOT_USED4",
		1: "STRING",
		2: "NUMBER",
	}
	DataType_value = map[string]int32{
		"NOT_USED4": 0,
		"STRING":    1,
		"NUMBER":    2,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[3].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[3]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{3}
}

// The FE needs certain information to be added by the BE enrichment process
// This has been reduced to a From/To statement:
// And all message historically will now be altered in the FE
type FromTo int32

const (
	FromTo_NOT_USED6 FromTo = 0 // Need unique enum values for proto (C requirement, we don't use C)
	FromTo_FROM      FromTo = 1
	FromTo_TO        FromTo = 2
	FromTo_CONTENT   FromTo = 3
)

// Enum value maps for FromTo.
var (
	FromTo_name = map[int32]string{
		0: "NOT_USED6",
		1: "FROM",
		2: "TO",
		3: "CONTENT",
	}
	FromTo_value = map[string]int32{
		"NOT_USED6": 0,
		"FROM":      1,
		"TO":        2,
		"CONTENT":   3,
	}
)

func (x FromTo) Enum() *FromTo {
	p := new(FromTo)
	*p = x
	return p
}

func (x FromTo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FromTo) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[4].Descriptor()
}

func (FromTo) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[4]
}

func (x FromTo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FromTo.Descriptor instead.
func (FromTo) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{4}
}

// TODO: update ParameterLabel and SourceType after discussion
type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label      ParameterLabel `protobuf:"varint,1,opt,name=Label,proto3,enum=notification.parameters.ParameterLabel" json:"Label,omitempty"`
	Value      string         `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Source     string         `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceType SourceType     `protobuf:"varint,4,opt,name=SourceType,proto3,enum=notification.parameters.SourceType" json:"SourceType,omitempty"`
	DataType   DataType       `protobuf:"varint,5,opt,name=DataType,proto3,enum=notification.parameters.DataType" json:"DataType,omitempty"`
	FromTo     FromTo         `protobuf:"varint,6,opt,name=FromTo,proto3,enum=notification.parameters.FromTo" json:"FromTo,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parameters_parameters_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_parameters_parameters_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetLabel() ParameterLabel {
	if x != nil {
		return x.Label
	}
	return ParameterLabel_NOT_USED3
}

func (x *Parameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Parameter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Parameter) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_NOT_USED7
}

func (x *Parameter) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_NOT_USED4
}

func (x *Parameter) GetFromTo() FromTo {
	if x != nil {
		return x.FromTo
	}
	return FromTo_NOT_USED6
}

var File_parameters_parameters_proto protoreflect.FileDescriptor

var file_parameters_parameters_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0xb5, 0x02, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x05, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x43, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x2e,
	0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x52, 0x06, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x2a, 0x3d,
	0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x37, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41,
	0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x41, 0x4c, 0x4c,
	0x45, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x59, 0x43, 0x10, 0x03, 0x2a, 0x39, 0x0a,
	0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x55,
	0x53, 0x45, 0x44, 0x38, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x52, 0x45, 0x42, 0x41,
	0x53, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x03, 0x2a, 0x6b, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x33, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x41, 0x54,
	0x45, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4d, 0x4f, 0x55, 0x4e,
	0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x4f, 0x52,
	0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x45, 0x53, 0x54, 0x49, 0x4e, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x41, 0x4d, 0x45, 0x10, 0x06, 0x2a, 0x31, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x34, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x36, 0x0a, 0x06, 0x46, 0x72, 0x6f, 0x6d,
	0x54, 0x6f, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x36, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x52, 0x4f, 0x4d, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x54,
	0x4f, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x03,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parameters_parameters_proto_rawDescOnce sync.Once
	file_parameters_parameters_proto_rawDescData = file_parameters_parameters_proto_rawDesc
)

func file_parameters_parameters_proto_rawDescGZIP() []byte {
	file_parameters_parameters_proto_rawDescOnce.Do(func() {
		file_parameters_parameters_proto_rawDescData = protoimpl.X.CompressGZIP(file_parameters_parameters_proto_rawDescData)
	})
	return file_parameters_parameters_proto_rawDescData
}

var file_parameters_parameters_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_parameters_parameters_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameters_parameters_proto_goTypes = []interface{}{
	(SourceType)(0),     // 0: notification.parameters.SourceType
	(Target)(0),         // 1: notification.parameters.Target
	(ParameterLabel)(0), // 2: notification.parameters.ParameterLabel
	(DataType)(0),       // 3: notification.parameters.DataType
	(FromTo)(0),         // 4: notification.parameters.FromTo
	(*Parameter)(nil),   // 5: notification.parameters.Parameter
}
var file_parameters_parameters_proto_depIdxs = []int32{
	2, // 0: notification.parameters.Parameter.Label:type_name -> notification.parameters.ParameterLabel
	0, // 1: notification.parameters.Parameter.SourceType:type_name -> notification.parameters.SourceType
	3, // 2: notification.parameters.Parameter.DataType:type_name -> notification.parameters.DataType
	4, // 3: notification.parameters.Parameter.FromTo:type_name -> notification.parameters.FromTo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_parameters_parameters_proto_init() }
func file_parameters_parameters_proto_init() {
	if File_parameters_parameters_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parameters_parameters_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parameters_parameters_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameters_parameters_proto_goTypes,
		DependencyIndexes: file_parameters_parameters_proto_depIdxs,
		EnumInfos:         file_parameters_parameters_proto_enumTypes,
		MessageInfos:      file_parameters_parameters_proto_msgTypes,
	}.Build()
	File_parameters_parameters_proto = out.File
	file_parameters_parameters_proto_rawDesc = nil
	file_parameters_parameters_proto_goTypes = nil
	file_parameters_parameters_proto_depIdxs = nil
}
