// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v6.32.1
// source: parameters/parameters.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "notification.parameters";

export enum SourceType {
  /** NOT_USED7 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED7 = 0,
  ADDRESS = 1,
  WALLET = 2,
  KYC = 3,
  COMMENT = 4,
  UNRECOGNIZED = -1,
}

export function sourceTypeFromJSON(object: any): SourceType {
  switch (object) {
    case 0:
    case "NOT_USED7":
      return SourceType.NOT_USED7;
    case 1:
    case "ADDRESS":
      return SourceType.ADDRESS;
    case 2:
    case "WALLET":
      return SourceType.WALLET;
    case 3:
    case "KYC":
      return SourceType.KYC;
    case 4:
    case "COMMENT":
      return SourceType.COMMENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SourceType.UNRECOGNIZED;
  }
}

export function sourceTypeToJSON(object: SourceType): string {
  switch (object) {
    case SourceType.NOT_USED7:
      return "NOT_USED7";
    case SourceType.ADDRESS:
      return "ADDRESS";
    case SourceType.WALLET:
      return "WALLET";
    case SourceType.KYC:
      return "KYC";
    case SourceType.COMMENT:
      return "COMMENT";
    case SourceType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Target {
  /** NOT_USED8 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED8 = 0,
  FIREBASE = 1,
  WEB = 2,
  EMAIL = 3,
  UNRECOGNIZED = -1,
}

export function targetFromJSON(object: any): Target {
  switch (object) {
    case 0:
    case "NOT_USED8":
      return Target.NOT_USED8;
    case 1:
    case "FIREBASE":
      return Target.FIREBASE;
    case 2:
    case "WEB":
      return Target.WEB;
    case 3:
    case "EMAIL":
      return Target.EMAIL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Target.UNRECOGNIZED;
  }
}

export function targetToJSON(object: Target): string {
  switch (object) {
    case Target.NOT_USED8:
      return "NOT_USED8";
    case Target.FIREBASE:
      return "FIREBASE";
    case Target.WEB:
      return "WEB";
    case Target.EMAIL:
      return "EMAIL";
    case Target.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ParameterLabel {
  /** NOT_USED3 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED3 = 0,
  /** ID - Generically usable ID field */
  ID = 1,
  /** DESCRIPTION - Generically usable DESCRIPTION field */
  DESCRIPTION = 2,
  DESTINATION = 3,
  CURRENCY = 50,
  MARKET = 51,
  DATETIME = 52,
  AMOUNT = 53,
  INITIATOR = 54,
  /** NAME - Generically usable NAME field */
  NAME = 55,
  UNRECOGNIZED = -1,
}

export function parameterLabelFromJSON(object: any): ParameterLabel {
  switch (object) {
    case 0:
    case "NOT_USED3":
      return ParameterLabel.NOT_USED3;
    case 1:
    case "ID":
      return ParameterLabel.ID;
    case 2:
    case "DESCRIPTION":
      return ParameterLabel.DESCRIPTION;
    case 3:
    case "DESTINATION":
      return ParameterLabel.DESTINATION;
    case 50:
    case "CURRENCY":
      return ParameterLabel.CURRENCY;
    case 51:
    case "MARKET":
      return ParameterLabel.MARKET;
    case 52:
    case "DATETIME":
      return ParameterLabel.DATETIME;
    case 53:
    case "AMOUNT":
      return ParameterLabel.AMOUNT;
    case 54:
    case "INITIATOR":
      return ParameterLabel.INITIATOR;
    case 55:
    case "NAME":
      return ParameterLabel.NAME;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ParameterLabel.UNRECOGNIZED;
  }
}

export function parameterLabelToJSON(object: ParameterLabel): string {
  switch (object) {
    case ParameterLabel.NOT_USED3:
      return "NOT_USED3";
    case ParameterLabel.ID:
      return "ID";
    case ParameterLabel.DESCRIPTION:
      return "DESCRIPTION";
    case ParameterLabel.DESTINATION:
      return "DESTINATION";
    case ParameterLabel.CURRENCY:
      return "CURRENCY";
    case ParameterLabel.MARKET:
      return "MARKET";
    case ParameterLabel.DATETIME:
      return "DATETIME";
    case ParameterLabel.AMOUNT:
      return "AMOUNT";
    case ParameterLabel.INITIATOR:
      return "INITIATOR";
    case ParameterLabel.NAME:
      return "NAME";
    case ParameterLabel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Parameter types for DataEvaluation: Sadly enums have to be unique, and we want to use an enum here to limit input/settings
 * on definition level and not on code level: PT_ is used in front of the parameter type to avoid conflicts
 */
export enum DataType {
  /** NOT_USED4 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED4 = 0,
  STRING = 1,
  NUMBER = 2,
  UNRECOGNIZED = -1,
}

export function dataTypeFromJSON(object: any): DataType {
  switch (object) {
    case 0:
    case "NOT_USED4":
      return DataType.NOT_USED4;
    case 1:
    case "STRING":
      return DataType.STRING;
    case 2:
    case "NUMBER":
      return DataType.NUMBER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DataType.UNRECOGNIZED;
  }
}

export function dataTypeToJSON(object: DataType): string {
  switch (object) {
    case DataType.NOT_USED4:
      return "NOT_USED4";
    case DataType.STRING:
      return "STRING";
    case DataType.NUMBER:
      return "NUMBER";
    case DataType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * The FE needs certain information to be added by the BE enrichment process
 * This has been reduced to a From/To statement:
 * And all message historically will now be altered in the FE
 */
export enum FromTo {
  /** NOT_USED6 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED6 = 0,
  FROM = 1,
  TO = 2,
  CONTENT = 3,
  UNRECOGNIZED = -1,
}

export function fromToFromJSON(object: any): FromTo {
  switch (object) {
    case 0:
    case "NOT_USED6":
      return FromTo.NOT_USED6;
    case 1:
    case "FROM":
      return FromTo.FROM;
    case 2:
    case "TO":
      return FromTo.TO;
    case 3:
    case "CONTENT":
      return FromTo.CONTENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FromTo.UNRECOGNIZED;
  }
}

export function fromToToJSON(object: FromTo): string {
  switch (object) {
    case FromTo.NOT_USED6:
      return "NOT_USED6";
    case FromTo.FROM:
      return "FROM";
    case FromTo.TO:
      return "TO";
    case FromTo.CONTENT:
      return "CONTENT";
    case FromTo.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Parameter {
  Label: ParameterLabel;
  Value: string;
  Source: string;
  SourceType: SourceType;
  DataType: DataType;
  FromTo: FromTo;
}

function createBaseParameter(): Parameter {
  return { Label: 0, Value: "", Source: "", SourceType: 0, DataType: 0, FromTo: 0 };
}

export const Parameter = {
  encode(message: Parameter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Label !== 0) {
      writer.uint32(8).int32(message.Label);
    }
    if (message.Value !== "") {
      writer.uint32(18).string(message.Value);
    }
    if (message.Source !== "") {
      writer.uint32(26).string(message.Source);
    }
    if (message.SourceType !== 0) {
      writer.uint32(32).int32(message.SourceType);
    }
    if (message.DataType !== 0) {
      writer.uint32(40).int32(message.DataType);
    }
    if (message.FromTo !== 0) {
      writer.uint32(48).int32(message.FromTo);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Parameter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParameter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Label = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Value = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Source = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.SourceType = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.DataType = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.FromTo = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Parameter {
    return {
      Label: isSet(object.Label) ? parameterLabelFromJSON(object.Label) : 0,
      Value: isSet(object.Value) ? globalThis.String(object.Value) : "",
      Source: isSet(object.Source) ? globalThis.String(object.Source) : "",
      SourceType: isSet(object.SourceType) ? sourceTypeFromJSON(object.SourceType) : 0,
      DataType: isSet(object.DataType) ? dataTypeFromJSON(object.DataType) : 0,
      FromTo: isSet(object.FromTo) ? fromToFromJSON(object.FromTo) : 0,
    };
  },

  toJSON(message: Parameter): unknown {
    const obj: any = {};
    if (message.Label !== 0) {
      obj.Label = parameterLabelToJSON(message.Label);
    }
    if (message.Value !== "") {
      obj.Value = message.Value;
    }
    if (message.Source !== "") {
      obj.Source = message.Source;
    }
    if (message.SourceType !== 0) {
      obj.SourceType = sourceTypeToJSON(message.SourceType);
    }
    if (message.DataType !== 0) {
      obj.DataType = dataTypeToJSON(message.DataType);
    }
    if (message.FromTo !== 0) {
      obj.FromTo = fromToToJSON(message.FromTo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Parameter>, I>>(base?: I): Parameter {
    return Parameter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Parameter>, I>>(object: I): Parameter {
    const message = createBaseParameter();
    message.Label = object.Label ?? 0;
    message.Value = object.Value ?? "";
    message.Source = object.Source ?? "";
    message.SourceType = object.SourceType ?? 0;
    message.DataType = object.DataType ?? 0;
    message.FromTo = object.FromTo ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
