// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: parameters/parameters.proto

package parameters

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_NOT_USED7 SourceType = 0 // Need unique enum values for proto (C requirement, we don't use C)
	SourceType_ADDRESS   SourceType = 1
	SourceType_WALLET    SourceType = 2
	SourceType_KYC       SourceType = 3
	SourceType_COMMENT   SourceType = 4
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "NOT_USED7",
		1: "ADDRESS",
		2: "WALLET",
		3: "KYC",
		4: "COMMENT",
	}
	SourceType_value = map[string]int32{
		"NOT_USED7": 0,
		"ADDRESS":   1,
		"WALLET":    2,
		"KYC":       3,
		"COMMENT":   4,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{0}
}

type Target int32

const (
	Target_NOT_USED8 Target = 0 // Need unique enum values for proto (C requirement, we don't use C)
	Target_FIREBASE  Target = 1
	Target_WEB       Target = 2
	Target_EMAIL     Target = 3
)

// Enum value maps for Target.
var (
	Target_name = map[int32]string{
		0: "NOT_USED8",
		1: "FIREBASE",
		2: "WEB",
		3: "EMAIL",
	}
	Target_value = map[string]int32{
		"NOT_USED8": 0,
		"FIREBASE":  1,
		"WEB":       2,
		"EMAIL":     3,
	}
)

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[1].Descriptor()
}

func (Target) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[1]
}

func (x Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target.Descriptor instead.
func (Target) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{1}
}

type ParameterLabel int32

const (
	ParameterLabel_NOT_USED3   ParameterLabel = 0 // Need unique enum values for proto (C requirement, we don't use C)
	ParameterLabel_ID          ParameterLabel = 1 // Generically usable ID field
	ParameterLabel_DESCRIPTION ParameterLabel = 2 // Generically usable DESCRIPTION field
	ParameterLabel_DESTINATION ParameterLabel = 3
	ParameterLabel_CURRENCY    ParameterLabel = 50
	ParameterLabel_MARKET      ParameterLabel = 51
	ParameterLabel_DATETIME    ParameterLabel = 52
	ParameterLabel_AMOUNT      ParameterLabel = 53
	ParameterLabel_INITIATOR   ParameterLabel = 54
	ParameterLabel_NAME        ParameterLabel = 55 // Generically usable NAME field
)

// Enum value maps for ParameterLabel.
var (
	ParameterLabel_name = map[int32]string{
		0:  "NOT_USED3",
		1:  "ID",
		2:  "DESCRIPTION",
		3:  "DESTINATION",
		50: "CURRENCY",
		51: "MARKET",
		52: "DATETIME",
		53: "AMOUNT",
		54: "INITIATOR",
		55: "NAME",
	}
	ParameterLabel_value = map[string]int32{
		"NOT_USED3":   0,
		"ID":          1,
		"DESCRIPTION": 2,
		"DESTINATION": 3,
		"CURRENCY":    50,
		"MARKET":      51,
		"DATETIME":    52,
		"AMOUNT":      53,
		"INITIATOR":   54,
		"NAME":        55,
	}
)

func (x ParameterLabel) Enum() *ParameterLabel {
	p := new(ParameterLabel)
	*p = x
	return p
}

func (x ParameterLabel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParameterLabel) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[2].Descriptor()
}

func (ParameterLabel) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[2]
}

func (x ParameterLabel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParameterLabel.Descriptor instead.
func (ParameterLabel) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{2}
}

// Parameter types for DataEvaluation: Sadly enums have to be unique, and we want to use an enum here to limit input/settings
// on definition level and not on code level: PT_ is used in front of the parameter type to avoid conflicts
type DataType int32

const (
	DataType_NOT_USED4 DataType = 0 // Need unique enum values for proto (C requirement, we don't use C)
	DataType_STRING    DataType = 1
	DataType_NUMBER    DataType = 2
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "NOT_USED4",
		1: "STRING",
		2: "NUMBER",
	}
	DataType_value = map[string]int32{
		"NOT_USED4": 0,
		"STRING":    1,
		"NUMBER":    2,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[3].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[3]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{3}
}

// The FE needs certain information to be added by the BE enrichment process
// This has been reduced to a From/To statement:
// And all message historically will now be altered in the FE
type FromTo int32

const (
	FromTo_NOT_USED6 FromTo = 0 // Need unique enum values for proto (C requirement, we don't use C)
	FromTo_FROM      FromTo = 1
	FromTo_TO        FromTo = 2
	FromTo_CONTENT   FromTo = 3
)

// Enum value maps for FromTo.
var (
	FromTo_name = map[int32]string{
		0: "NOT_USED6",
		1: "FROM",
		2: "TO",
		3: "CONTENT",
	}
	FromTo_value = map[string]int32{
		"NOT_USED6": 0,
		"FROM":      1,
		"TO":        2,
		"CONTENT":   3,
	}
)

func (x FromTo) Enum() *FromTo {
	p := new(FromTo)
	*p = x
	return p
}

func (x FromTo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FromTo) Descriptor() protoreflect.EnumDescriptor {
	return file_parameters_parameters_proto_enumTypes[4].Descriptor()
}

func (FromTo) Type() protoreflect.EnumType {
	return &file_parameters_parameters_proto_enumTypes[4]
}

func (x FromTo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FromTo.Descriptor instead.
func (FromTo) EnumDescriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{4}
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         ParameterLabel         `protobuf:"varint,1,opt,name=Label,proto3,enum=notification.parameters.ParameterLabel" json:"Label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	SourceType    SourceType             `protobuf:"varint,4,opt,name=SourceType,proto3,enum=notification.parameters.SourceType" json:"SourceType,omitempty"`
	DataType      DataType               `protobuf:"varint,5,opt,name=DataType,proto3,enum=notification.parameters.DataType" json:"DataType,omitempty"`
	FromTo        FromTo                 `protobuf:"varint,6,opt,name=FromTo,proto3,enum=notification.parameters.FromTo" json:"FromTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_parameters_parameters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_parameters_parameters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_parameters_parameters_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetLabel() ParameterLabel {
	if x != nil {
		return x.Label
	}
	return ParameterLabel_NOT_USED3
}

func (x *Parameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Parameter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Parameter) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_NOT_USED7
}

func (x *Parameter) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_NOT_USED4
}

func (x *Parameter) GetFromTo() FromTo {
	if x != nil {
		return x.FromTo
	}
	return FromTo_NOT_USED6
}

var File_parameters_parameters_proto protoreflect.FileDescriptor

const file_parameters_parameters_proto_rawDesc = "" +
	"\n" +
	"\x1bparameters/parameters.proto\x12\x17notification.parameters\"\xb5\x02\n" +
	"\tParameter\x12=\n" +
	"\x05Label\x18\x01 \x01(\x0e2'.notification.parameters.ParameterLabelR\x05Label\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x12\x16\n" +
	"\x06Source\x18\x03 \x01(\tR\x06Source\x12C\n" +
	"\n" +
	"SourceType\x18\x04 \x01(\x0e2#.notification.parameters.SourceTypeR\n" +
	"SourceType\x12=\n" +
	"\bDataType\x18\x05 \x01(\x0e2!.notification.parameters.DataTypeR\bDataType\x127\n" +
	"\x06FromTo\x18\x06 \x01(\x0e2\x1f.notification.parameters.FromToR\x06FromTo*J\n" +
	"\n" +
	"SourceType\x12\r\n" +
	"\tNOT_USED7\x10\x00\x12\v\n" +
	"\aADDRESS\x10\x01\x12\n" +
	"\n" +
	"\x06WALLET\x10\x02\x12\a\n" +
	"\x03KYC\x10\x03\x12\v\n" +
	"\aCOMMENT\x10\x04*9\n" +
	"\x06Target\x12\r\n" +
	"\tNOT_USED8\x10\x00\x12\f\n" +
	"\bFIREBASE\x10\x01\x12\a\n" +
	"\x03WEB\x10\x02\x12\t\n" +
	"\x05EMAIL\x10\x03*\x96\x01\n" +
	"\x0eParameterLabel\x12\r\n" +
	"\tNOT_USED3\x10\x00\x12\x06\n" +
	"\x02ID\x10\x01\x12\x0f\n" +
	"\vDESCRIPTION\x10\x02\x12\x0f\n" +
	"\vDESTINATION\x10\x03\x12\f\n" +
	"\bCURRENCY\x102\x12\n" +
	"\n" +
	"\x06MARKET\x103\x12\f\n" +
	"\bDATETIME\x104\x12\n" +
	"\n" +
	"\x06AMOUNT\x105\x12\r\n" +
	"\tINITIATOR\x106\x12\b\n" +
	"\x04NAME\x107*1\n" +
	"\bDataType\x12\r\n" +
	"\tNOT_USED4\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x02*6\n" +
	"\x06FromTo\x12\r\n" +
	"\tNOT_USED6\x10\x00\x12\b\n" +
	"\x04FROM\x10\x01\x12\x06\n" +
	"\x02TO\x10\x02\x12\v\n" +
	"\aCONTENT\x10\x03B;Z9github.com/sologenic/com-fs-notification-model/parametersb\x06proto3"

var (
	file_parameters_parameters_proto_rawDescOnce sync.Once
	file_parameters_parameters_proto_rawDescData []byte
)

func file_parameters_parameters_proto_rawDescGZIP() []byte {
	file_parameters_parameters_proto_rawDescOnce.Do(func() {
		file_parameters_parameters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parameters_parameters_proto_rawDesc), len(file_parameters_parameters_proto_rawDesc)))
	})
	return file_parameters_parameters_proto_rawDescData
}

var file_parameters_parameters_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_parameters_parameters_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameters_parameters_proto_goTypes = []any{
	(SourceType)(0),     // 0: notification.parameters.SourceType
	(Target)(0),         // 1: notification.parameters.Target
	(ParameterLabel)(0), // 2: notification.parameters.ParameterLabel
	(DataType)(0),       // 3: notification.parameters.DataType
	(FromTo)(0),         // 4: notification.parameters.FromTo
	(*Parameter)(nil),   // 5: notification.parameters.Parameter
}
var file_parameters_parameters_proto_depIdxs = []int32{
	2, // 0: notification.parameters.Parameter.Label:type_name -> notification.parameters.ParameterLabel
	0, // 1: notification.parameters.Parameter.SourceType:type_name -> notification.parameters.SourceType
	3, // 2: notification.parameters.Parameter.DataType:type_name -> notification.parameters.DataType
	4, // 3: notification.parameters.Parameter.FromTo:type_name -> notification.parameters.FromTo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_parameters_parameters_proto_init() }
func file_parameters_parameters_proto_init() {
	if File_parameters_parameters_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parameters_parameters_proto_rawDesc), len(file_parameters_parameters_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameters_parameters_proto_goTypes,
		DependencyIndexes: file_parameters_parameters_proto_depIdxs,
		EnumInfos:         file_parameters_parameters_proto_enumTypes,
		MessageInfos:      file_parameters_parameters_proto_msgTypes,
	}.Build()
	File_parameters_parameters_proto = out.File
	file_parameters_parameters_proto_goTypes = nil
	file_parameters_parameters_proto_depIdxs = nil
}
