// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v5.29.1
// source: formats/formats.proto

/* eslint-disable */

export const protobufPackage = "notification.formats";

/** Base formatting of the message, used by the parsers */
export enum Format {
  /** NOT_USED2 - Need unique enum values for proto (C requirement, we don't use C) */
  NOT_USED2 = 0,
  TEXT = 1,
  HTML = 2,
  MARKDOWNV2 = 3,
  UNRECOGNIZED = -1,
}

export function formatFromJSON(object: any): Format {
  switch (object) {
    case 0:
    case "NOT_USED2":
      return Format.NOT_USED2;
    case 1:
    case "TEXT":
      return Format.TEXT;
    case 2:
    case "HTML":
      return Format.HTML;
    case 3:
    case "MARKDOWNV2":
      return Format.MARKDOWNV2;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Format.UNRECOGNIZED;
  }
}

export function formatToJSON(object: Format): string {
  switch (object) {
    case Format.NOT_USED2:
      return "NOT_USED2";
    case Format.TEXT:
      return "TEXT";
    case Format.HTML:
      return "HTML";
    case Format.MARKDOWNV2:
      return "MARKDOWNV2";
    case Format.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
